export const Action = {
    DURACIONES_EDITED_ITEM: "DURACIONES_EDITED_ITEM",
    DURACIONES_IS_NEW_ITEM: "DURACIONES_IS_NEW_ITEM",
};
export const Mutation = {
    DURACIONES_EDITED_ITEM: "DURACIONES_EDITED_ITEM",
    DURACIONES_IS_NEW_ITEM: "DURACIONES_IS_NEW_ITEM",
};
