export const Action = {
    TRABAJADORES_EDIT_DIALOG: "TRABAJADORES_EDIT_DIALOG",
    GRUPOS_IMPORT_DIALOG: "GRUPOS_IMPORT_DIALOG",
};
export const Mutation = {
    TRABAJADORES_EDIT_DIALOG: "TRABAJADORES_EDIT_DIALOG",
    GRUPOS_IMPORT_DIALOG: "GRUPOS_IMPORT_DIALOG",
};