export const Action = {
    TRABAJADORES_EDITED_ITEM: "TRABAJADORES_EDITED_ITEM",
    TRABAJADORES_IS_NEW_ITEM: "TRABAJADORES_IS_NEW_ITEM",
};
export const Mutation = {
    TRABAJADORES_EDITED_ITEM: "TRABAJADORES_EDITED_ITEM",
    TRABAJADORES_IS_NEW_ITEM: "TRABAJADORES_IS_NEW_ITEM",
};
