export const Action = {
    CLIENTES_EMPRESAS: "CLIENTES_EMPRESAS",
    CLIENTES_EMPRESAS_ACT: "CLIENTES_EMPRESAS_ACT",
    CLIENTES_EMPRESAS_RELOAD: "CLIENTES_EMPRESAS_RELOAD",
    CLIENTES_EMPRESAS_NEW: "CLIENTES_EMPRESAS_NEW",
    CLIENTES_EMPRESAS_DELETE: "CLIENTES_EMPRESAS_DELETE",
    CLIENTES_EMPRESAS_UPDATE_LOGO: "CLIENTES_EMPRESAS_UPDATE_LOGO",
    CLIENTES_EMPRESAS_DOWNLOAD_LOGO: "CLIENTES_EMPRESAS_DOWNLOAD_LOGO",
    CLIENTES_EMPRESAS_DELETE_LOGO: "CLIENTES_EMPRESAS_DELETE_LOGO",
};
export const Mutation = {
    CLIENTES_EMPRESAS: "CLIENTES_EMPRESAS",
    CLIENTES_EMPRESAS_ACT: "CLIENTES_EMPRESAS_ACT",
    CLIENTES_EMPRESAS_NEW: "CLIENTES_EMPRESAS_NEW",
    CLIENTES_EMPRESAS_DELETE: "CLIENTES_EMPRESAS_DELETE",
    CLIENTES_EMPRESAS_LOGO: "CLIENTES_EMPRESAS_LOGO",
    CLIENTES_EMPRESAS_DELETE_LOGO: "CLIENTES_EMPRESAS_DELETE_LOGO",
};