export const Action = {
    DEPARTAMENTOS: "DEPARTAMENTOS",    
    DEPARTAMENTOS_TAG: "DEPARTAMENTOS_TAG",
};
export const Mutation = {
    DEPARTAMENTOS: "DEPARTAMENTOS",    
    DEPARTAMENTOS_TAG: "DEPARTAMENTOS_TAG",
};