export const Action = {
    CLIENTES_EMPRESAS_EDITED_ITEM: "CLIENTES_EMPRESAS_EDITED_ITEM",
    CLIENTES_EMPRESAS_IS_NEW_ITEM: "CLIENTES_EMPRESAS_IS_NEW_ITEM",
};
export const Mutation = {
    CLIENTES_EMPRESAS_EDITED_ITEM: "CLIENTES_EMPRESAS_EDITED_ITEM",
    CLIENTES_EMPRESAS_IS_NEW_ITEM: "CLIENTES_EMPRESAS_IS_NEW_ITEM",
};
