export const Action = {
    CAPACITACIONES_EDITED_ITEM: "CAPACITACIONES_EDITED_ITEM",
    CAPACITACIONES_IS_NEW_ITEM: "CAPACITACIONES_IS_NEW_ITEM",
};
export const Mutation = {
    CAPACITACIONES_EDITED_ITEM: "CAPACITACIONES_EDITED_ITEM",
    CAPACITACIONES_IS_NEW_ITEM: "CAPACITACIONES_IS_NEW_ITEM",
};
