export const Action = {
    SUB_AREAS_OCUPACIONES: "SUB_AREAS_OCUPACIONES",
    SUB_AREAS_OCUPACIONES_VFORMATTED: "SUB_AREAS_OCUPACIONES_VFORMATTED",
};
export const Mutation = {
    SUB_AREAS_OCUPACIONES: "SUB_AREAS_OCUPACIONES",
    SUB_AREAS_OCUPACIONES_VFORMATTED: "SUB_AREAS_OCUPACIONES_VFORMATTED",
};