export const Action = {
    CAPACITACIONES: "CAPACITACIONES",
    CAPACITACIONES_ACT: "CAPACITACIONES_ACT",
    CAPACITACIONES_ACT_CURSOS_FECHAS: "CAPACITACIONES_ACT_CURSOS_FECHAS",
    CAPACITACIONES_ACT_CURSOS_CAPACITADORES: "CAPACITACIONES_ACT_CURSOS_CAPACITADORES",
    CAPACITACIONES_NEW: "CAPACITACIONES_NEW",
    CAPACITACIONES_DELETE: "CAPACITACIONES_DELETE",
    CAPACITACION_CURSOS: "CAPACITACION_CURSOS",
    CAPACITACION_DOWNLOAD_DC3: "CAPACITACION_DOWNLOAD_DC3",
    CAPACITACION_DOWNLOAD_REPORT: "CAPACITACION_DOWNLOAD_REPORT",
    CAPACITACION_DOWNLOAD_CERTIFICADO: "CAPACITACION_DOWNLOAD_CERTIFICADO"
};
export const Mutation = {
    CAPACITACIONES: "CAPACITACIONES",
    CAPACITACIONES_ACT: "CAPACITACIONES_ACT",
    CAPACITACIONES_NEW: "CAPACITACIONES_NEW",
    CAPACITACIONES_DELETE: "CAPACITACIONES_DELETE",
    CAPACITACION_CURSOS: "CAPACITACION_CURSOS",
};