export const Action = {
    CAPACITADORES_EDITED_ITEM: "CAPACITADORES_EDITED_ITEM",
    CAPACITADORES_IS_NEW_ITEM: "CAPACITADORES_IS_NEW_ITEM",
};
export const Mutation = {
    CAPACITADORES_EDITED_ITEM: "CAPACITADORES_EDITED_ITEM",
    CAPACITADORES_IS_NEW_ITEM: "CAPACITADORES_IS_NEW_ITEM",
};
